Repository atlp-rwanda/wolves-bn-backend, pull requests merged in 2020-09, with the labels that each got.

#2 #174772162: setting up coveralls
  .coveralls.yml
Labels: Ready for Review

#3 #174772156 Configure PostgreSQL and Sequelize ORM
  .sequelizerc
  package-lock.json
  package.json
  src/config/config.js
  src/controllers/index.js
  src/database/migrations/20200914165142-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/routes/index.js
Labels: Ready for Review

#4 #174772160: setup travis Ci
  .travis.yml
  README.md
Labels: Ready for Review

#6 Added the eslint file and the hound.yml file for houndCI
  .babelrc
  .eslintrc.json
  .hound.yml
  package-lock.json
  package.json
  src/index.js
  src/routes/index.js
Labels: needs review

#8 Fixing the linting problem in index.js controller
  .eslintrc.json
  README.md
  package-lock.json
  src/config/config.js
  src/controllers/index.js
  src/database/models/index.js
  src/database/models/user.js
  src/routes/index.js
Labels: needs review

#10 #174772209 Setup API documentation using swagger
  example.env
  package.json
  src/index.js
  swagger.json
Labels: Ready for Review

#5 #[174772157] [setup unit test]
  .eslintrc.json
  .gitignore
  .jshintrc
  package-lock.json
  package.json
  src/app.js
  test/file.test.js
Labels: Ready for Review

#11 ch(coveralls): added the coveralls badge to README
  README.md
Labels: Ready for Review

#13 #174772162 fix coveralls build
  .coveralls.yml
  package-lock.json
  package.json
Labels: Ready for Review

#12 #174836393 Update Sequelize configurations to use environment variable in production
  src/config/config.js
Labels: Ready to be viewed by TTL

#14 adding user registration endpoint
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  procfile
  src/config/config.js
  src/controllers/index.js
  src/controllers/user.js
  src/database/migrations/20200921152341-create-user.js
  src/database/models/user.js
  src/index.js
  src/middleware/userValidation.js
  src/routes/index.js
  src/utils/jwtToken.js
  swagger.json
  test/user.test.js
  wolvesbnbackend.session.sql
Labels: WIP

#19 #174772217: forgot and reset password endpoints
  .gitignore
  example.env
  package-lock.json
  package.json
  src/controllers/password.js
  src/database/migrations/20200921152341-create-user.js
  src/database/models/user.js
  src/routes/index.js
  swagger.json
  test/resetPassword.test.js
  test/user.test.js
Labels: Ready for Review

#20 #174772216 User authentication via facebook and google
  example.env
  package-lock.json
  package.json
  src/config/config.js
  src/config/passport.js
  src/controllers/userAuth.js
  src/database/migrations/20200914165142-create-user.js
  src/database/migrations/20200921152341-create-user.js
  src/database/models/user.js
  src/index.js
  src/routes/index.js
  swagger.json
  test/userAuth.test.js
Labels: Ready to be viewed by the classmates

#18 user-receive-mail-after registration-174772212
  connections.session.sql
  example.env
  package.json
  src/controllers/sendMail.js
  src/controllers/user.js
  src/database/migrations/20200921152341-create-user.js
  src/database/models/user.js
  src/routes/index.js
  swagger.json
  test/resetPassword.test.js
  test/sendMail.test.js
  test/user.test.js
Labels: Ready for Review

#22 Bug fix documentation 175017615
  swagger.json
Labels: Bug Fix

#23 #174772221 user should be able to make trip request
  src/database/migrations/20200928122621-create-trip.js
  src/database/migrations/20200929090340-create-location.js
  src/database/models/location.js
  src/database/models/trip.js
  src/database/models/users.js
  src/database/seeders/20200928140353-demo-trip.js
  src/database/seeders/20200929104539-demo-location.js
Labels: Ready to be viewed by TTL
